version: '3.4'

services:
  customerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

